# Generated by Django 6.0.3 on 2026-03-19 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.CharField(choices=[('starter', 'Starter'), ('profissional', 'Profissional'), ('premium', 'Premium')], max_length=50, unique=True, verbose_name='Identificador')),
                ('monthly_query_limit', models.IntegerField(blank=True, help_text='Deixe em branco para ilimitado', null=True, verbose_name='Limite Mensal de Consultas')),
                ('has_legal_basis', models.BooleanField(default=False, verbose_name='Ver Base Legal')),
                ('has_favorites', models.BooleanField(default=False, verbose_name='Favoritos')),
                ('has_history', models.BooleanField(default=False, verbose_name='Histórico')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='Acesso à API')),
                ('price_brl', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (R$)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['price_brl'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('canceled', 'Cancelado'), ('past_due', 'Inadimplente'), ('trial', 'Trial')], default='trial', max_length=20, verbose_name='Status')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.plan', verbose_name='Plano')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
