# Generated by Django 6.0.3 on 2026-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Cliente Asaas'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='asaas_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Assinatura Asaas'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('annual', 'Anual')], default='monthly', max_length=10, verbose_name='Ciclo de Cobrança'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('starter', 'Starter'), ('profissional', 'Profissional'), ('premium', 'Premium')], max_length=50, unique=True, verbose_name='Identificador'),
        ),
    ]
