# -*- coding: utf-8 -*-
from django.core.management.base import BaseCommand

from apps.catalog.models import EsocialNature


# Tabela 03 oficial do eSocial — versão 10 (194 códigos ativos)
# Extraída de https://frontend.esocial.gov.br/adm/ em 2026-04-09
OFFICIAL_NATURES = [
    ('1000', 'Salário, vencimento, soldo', True),
    ('1001', 'Subsídio', True),
    ('1003', 'Horas extraordinárias', True),
    ('1004', 'Horas extraordinárias - Banco de horas', True),
    ('1005', 'Direito de arena', True),
    ('1006', 'Intervalos intra e inter jornadas não concedidos', True),
    ('1007', 'Luvas e premiações', True),
    ('1009', 'Salário-família - Complemento', True),
    ('1010', 'Salário in natura - Pagos em bens ou serviços', True),
    ('1011', 'Sobreaviso e prontidão', True),
    ('1012', 'Descanso semanal remunerado - DSR e feriado', True),
    ('1015', 'Adiantamento de férias', True),
    ('1016', 'Férias', True),
    ('1017', 'Terço constitucional de férias', True),
    ('1018', 'Férias - Abono ou gratificação de férias superior a 20 dias', True),
    ('1019', 'Terço constitucional de férias - Abono ou gratificação de férias superior a 20 dias', True),
    ('1022', 'Férias - Abono ou gratificação de férias não excedente a 20 dias', True),
    ('1023', 'Férias - Abono pecuniário', True),
    ('1024', 'Férias - Dobro na vigência do contrato', True),
    ('1040', 'Licença-prêmio', True),
    ('1041', 'Licença-prêmio indenizada', True),
    ('1050', 'Remuneração de dias de afastamento', True),
    ('1080', 'Stock option', True),
    ('1099', 'Outras verbas salariais', True),
    ('1201', 'Adicional de função / cargo confiança', True),
    ('1202', 'Adicional de insalubridade', True),
    ('1203', 'Adicional de periculosidade', True),
    ('1204', 'Adicional de transferência', True),
    ('1205', 'Adicional noturno', True),
    ('1206', 'Adicional por tempo de serviço', True),
    ('1207', 'Comissões, porcentagens, produção', True),
    ('1208', 'Gueltas ou gorjetas - Repassadas por fornecedores ou clientes', True),
    ('1209', 'Gueltas ou gorjetas - Repassadas pelo empregador', True),
    ('1210', 'Gratificação por acordo ou convenção coletiva', True),
    ('1211', 'Gratificações', True),
    ('1212', 'Gratificações ou outras verbas de natureza permanente', True),
    ('1213', 'Gratificações ou outras verbas de natureza transitória', True),
    ('1214', 'Adicional de penosidade', True),
    ('1215', 'Adicional de unidocência', True),
    ('1216', 'Adicional de localidade', True),
    ('1217', 'Gratificação de curso/concurso', True),
    ('1225', 'Quebra de caixa', True),
    ('1230', 'Remuneração do dirigente sindical', True),
    ('1299', 'Outros adicionais', True),
    ('1300', 'PLR - Participação em Lucros ou Resultados', False),
    ('1350', 'Bolsa de estudo - Estagiário', False),
    ('1351', 'Bolsa de estudo - Médico residente', False),
    ('1352', 'Bolsa de estudo ou pesquisa', False),
    ('1401', 'Abono', False),
    ('1402', 'Abono PIS/PASEP', False),
    ('1403', 'Abono legal', False),
    ('1404', 'Auxílio babá', False),
    ('1405', 'Assistência médica', False),
    ('1406', 'Auxílio-creche', False),
    ('1407', 'Auxílio-educação', False),
    ('1409', 'Salário-família', False),
    ('1410', 'Auxílio - Locais de difícil acesso', False),
    ('1411', 'Auxílio-natalidade', False),
    ('1412', 'Abono permanência', False),
    ('1601', 'Ajuda de custo - Aeronauta', False),
    ('1602', 'Ajuda de custo de transferência', False),
    ('1603', 'Ajuda de custo', False),
    ('1619', 'Ajuda compensatória - Programa Emergencial de Manutenção do Emprego e da Renda', False),
    ('1620', 'Ressarcimento de despesas pelo uso de veículo próprio', False),
    ('1621', 'Ressarcimento de despesas de viagem, exceto despesas com veículos', False),
    ('1623', 'Ressarcimento de provisão', False),
    ('1629', 'Ressarcimento de outras despesas', False),
    ('1650', 'Diárias de viagem', False),
    ('1799', 'Alimentação concedida em pecúnia com caráter indenizatório', False),
    ('1800', 'Alimentação concedida em pecúnia com caráter salarial', True),
    ('1802', 'Etapas (marítimos)', True),
    ('1805', 'Moradia', True),
    ('1806', 'Alimentação em ticket ou cartão, vinculada ao PAT', False),
    ('1807', 'Alimentação em ticket ou cartão, não vinculada ao PAT', True),
    ('1808', 'Cesta básica ou refeição, vinculada ao PAT', False),
    ('1809', 'Cesta básica ou refeição, não vinculada ao PAT', True),
    ('1810', 'Vale-transporte ou auxílio-transporte com caráter indenizatório', False),
    ('1811', 'Auxílio-transporte ou auxílio-combustível com caráter salarial', True),
    ('1899', 'Outros auxílios', False),
    ('1901', 'Juros e/ou atualização monetária', False),
    ('2501', 'Prêmios', False),
    ('2510', 'Direitos autorais e intelectuais', False),
    ('2801', 'Quarentena remunerada', False),
    ('2901', 'Empréstimos', False),
    ('2903', 'Vestuário e equipamentos', False),
    ('2930', 'Insuficiência de saldo', False),
    ('2999', 'Arredondamentos', False),
    ('3501', 'Remuneração por prestação de serviços', True),
    ('3505', 'Retiradas (pró-labore) de diretores empregados', True),
    ('3506', 'Retiradas (pró-labore) de diretores não empregados', True),
    ('3508', 'Retiradas (pró-labore) de proprietários ou sócios', True),
    ('3509', 'Honorários a conselheiros', True),
    ('3510', 'Gratificação (jeton)', True),
    ('3511', 'Gratificação eleitoral', True),
    ('3520', 'Remuneração de cooperado', True),
    ('3525', 'Côngruas, prebendas e afins', True),
    ('4010', 'Complementação salarial de auxílio-doença', True),
    ('4011', 'Complemento de salário-mínimo - RPPS', True),
    ('4050', 'Salário-maternidade', True),
    ('4051', 'Salário-maternidade - 13° salário', True),
    ('5001', '13º salário', True),
    ('5005', '13° salário complementar', True),
    ('5501', 'Adiantamento de salário', False),
    ('5504', '13º salário - Adiantamento', False),
    ('5510', 'Adiantamento de benefícios previdenciários', False),
    ('6000', 'Saldo de salários na rescisão contratual', True),
    ('6001', '13º salário relativo ao aviso prévio indenizado', True),
    ('6002', '13° salário proporcional na rescisão', True),
    ('6003', 'Indenização compensatória do aviso prévio', False),
    ('6004', 'Férias - Dobro na rescisão', False),
    ('6006', 'Férias proporcionais', False),
    ('6007', 'Férias vencidas na rescisão', False),
    ('6101', 'Indenização compensatória - Multa rescisória 20 ou 40% (CF/88)', False),
    ('6102', 'Indenização do art. 9º da Lei 7.238/1984', False),
    ('6103', 'Indenização do art. 14 da Lei 5.889/1973', False),
    ('6104', 'Indenização do art. 479 da CLT', False),
    ('6105', 'Indenização recebida a título de incentivo a demissão', False),
    ('6106', 'Multa do art. 477 da CLT', False),
    ('6107', 'Indenização por quebra de estabilidade', False),
    ('6108', 'Tempo de espera do motorista profissional', False),
    ('6119', 'Indenização rescisória - Programa Emergencial de Manutenção do Emprego e da Renda', False),
    ('6129', 'Outras verbas não remuneratórias (indenizatórias ou multas)', False),
    ('6901', 'Desconto do aviso prévio', False),
    ('6904', 'Multa prevista no art. 480 da CLT', False),
    ('7001', 'Proventos', False),
    ('7002', 'Proventos - Pensão por morte Civil', False),
    ('7003', 'Proventos - Reserva', False),
    ('7004', 'Proventos - Reforma', False),
    ('7005', 'Pensão Militar', False),
    ('7006', 'Auxílio-reclusão', False),
    ('7007', 'Pensões especiais', False),
    ('7008', 'Complementação de aposentadoria/ pensão', False),
    ('9200', 'Desconto de adiantamentos', False),
    ('9201', 'Contribuição previdenciária', False),
    ('9202', 'Contribuição militar', False),
    ('9203', 'Imposto de Renda Retido na Fonte', False),
    ('9205', 'Provisão de contribuição previdenciária', False),
    ('9207', 'Faltas', False),
    ('9208', 'Atrasos', False),
    ('9209', 'Faltas ou atrasos', False),
    ('9210', 'DSR s/faltas e atrasos', False),
    ('9211', 'DSR sobre faltas', False),
    ('9212', 'DSR sobre atrasos', False),
    ('9213', 'Pensão alimentícia', False),
    ('9214', '13° salário - Desconto de adiantamento', False),
    ('9216', 'Desconto de vale-transporte', False),
    ('9217', 'Contribuição a Outras Entidades e Fundos', False),
    ('9218', 'Retenções judiciais', False),
    ('9219', 'Desconto de assistência médica ou odontológica - Plano coletivo empresarial', False),
    ('9221', 'Desconto de férias', False),
    ('9222', 'Desconto de outros impostos e contribuições', False),
    ('9223', 'Previdência complementar - Parte do empregado', False),
    ('9224', 'FAPI - Parte do empregado', False),
    ('9225', 'Previdência complementar - Parte do servidor', False),
    ('9226', 'Desconto de férias - Abono', False),
    ('9230', 'Contribuição sindical laboral', False),
    ('9231', 'Mensalidade sindical ou associativa', False),
    ('9232', 'Contribuição sindical - Assistencial', False),
    ('9233', 'Contribuição sindical - Confederativa', False),
    ('9240', 'Alimentação concedida em pecúnia - Desconto', False),
    ('9241', 'Alimentação em ticket ou cartão, vinculada ao PAT - Desconto', False),
    ('9242', 'Alimentação em ticket ou cartão, não vinculada ao PAT - Desconto', False),
    ('9243', 'Cesta básica ou refeição, vinculada ao PAT - Desconto', False),
    ('9244', 'Cesta básica ou refeição, não vinculada ao PAT - Desconto', False),
    ('9250', 'Seguro de vida - Desconto', False),
    ('9253', 'Empréstimos eConsignado - Desconto', False),
    ('9254', 'Empréstimos consignados - Desconto', False),
    ('9255', 'Empréstimos do empregador - Desconto', False),
    ('9258', 'Convênios', False),
    ('9260', 'FIES - Desconto', False),
    ('9270', 'Danos e prejuízos causados pelo trabalhador', False),
    ('9291', 'Abate-teto', False),
    ('9292', 'Ressarcimento ao erário', False),
    ('9293', 'Honorários advocatícios', False),
    ('9294', 'Redutor EC 41/03', False),
    ('9299', 'Outros descontos', False),
    ('9901', 'Base de cálculo da contribuição previdenciária', False),
    ('9902', 'Total da base de cálculo do FGTS', False),
    ('9903', 'Total da base de cálculo do IRRF', False),
    ('9904', 'Total da base de cálculo do FGTS rescisório', False),
    ('9905', 'Serviço militar', False),
    ('9906', 'Remuneração no exterior', False),
    ('9907', 'Total da contribuição da previdenciária patronal - RPPS', False),
    ('9908', 'FGTS - Depósito', False),
    ('9910', 'Seguros', False),
    ('9911', 'Assistência Médica', False),
    ('9912', 'Desconto de assistência médica ou odontológica - Plano diferente de coletivo empresarial', False),
    ('9930', 'Salário-maternidade pago pela Previdência Social', False),
    ('9931', 'Salário-maternidade pago pela Previdência Social - 13° salário', False),
    ('9932', 'Auxílio-doença acidentário', False),
    ('9933', 'Auxílio-doença', False),
    ('9938', 'Isenção IRRF - 65 anos', False),
    ('9939', 'Outros valores tributáveis', False),
    ('9989', 'Outros valores informativos', False),
]


class Command(BaseCommand):
    help = 'Cria/atualiza as 194 naturezas oficiais da Tabela 03 do eSocial'

    def handle(self, *args, **options):
        created = 0
        updated = 0

        for code, description, is_salary in OFFICIAL_NATURES:
            _, was_created = EsocialNature.objects.update_or_create(
                code=code,
                defaults={
                    'description': description,
                    'is_salary_nature': is_salary,
                },
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f'Naturezas eSocial: {created} criadas, {updated} atualizadas '
            f'(total: {len(OFFICIAL_NATURES)})',
        ))
