# Generated by Django 6.0.3 on 2026-03-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextualRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_description', models.CharField(max_length=500, verbose_name='Condição')),
                ('condition_key', models.CharField(help_text='Ex: regime_tributario, tipo_empresa', max_length=100, verbose_name='Chave da Condição')),
                ('condition_value', models.CharField(help_text='Ex: simples, mei', max_length=100, verbose_name='Valor da Condição')),
                ('override_inss', models.BooleanField(blank=True, null=True, verbose_name='Substitui INSS')),
                ('override_fgts', models.BooleanField(blank=True, null=True, verbose_name='Substitui FGTS')),
                ('override_irrf', models.BooleanField(blank=True, null=True, verbose_name='Substitui IRRF')),
                ('explanation', models.TextField(blank=True, verbose_name='Explicação da Regra')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextual_rules', to='catalog.rubric', verbose_name='Rubrica')),
            ],
            options={
                'verbose_name': 'Regra Contextual',
                'verbose_name_plural': 'Regras Contextuais',
            },
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inss', models.BooleanField(verbose_name='Incide INSS')),
                ('fgts', models.BooleanField(verbose_name='Incide FGTS')),
                ('irrf', models.BooleanField(verbose_name='Incide IRRF')),
                ('inss_observation', models.TextField(blank=True, verbose_name='Observação INSS')),
                ('fgts_observation', models.TextField(blank=True, verbose_name='Observação FGTS')),
                ('irrf_observation', models.TextField(blank=True, verbose_name='Observação IRRF')),
                ('risk_level', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto')], default='low', help_text='Risco de autuação em caso de erro nesta rubrica', max_length=10, verbose_name='Nível de Risco')),
                ('recently_changed', models.BooleanField(default=False, help_text='Sinaliza ao usuário que houve mudança legislativa recente', verbose_name='Alterado Recentemente')),
                ('change_note', models.TextField(blank=True, verbose_name='Nota de Alteração')),
                ('change_date', models.DateField(blank=True, null=True, verbose_name='Data da Alteração')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rubric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incidence', to='catalog.rubric', verbose_name='Rubrica')),
            ],
            options={
                'verbose_name': 'Incidência',
                'verbose_name_plural': 'Incidências',
            },
        ),
    ]
