# Generated by Django 6.0.3 on 2026-03-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='iss',
            field=models.BooleanField(default=False, verbose_name='Incide ISS'),
        ),
        migrations.AddField(
            model_name='incidence',
            name='iss_observation',
            field=models.TextField(blank=True, verbose_name='Observação ISS'),
        ),
    ]
