# Generated by Django 6.0.3 on 2026-03-20 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Cliente MEI, Empresa Simples Nacional, Empregado Doméstico', max_length=100, verbose_name='Nome do Perfil')),
                ('context', models.JSONField(default=dict, help_text='Chaves e valores de contexto para análise (ex: {"regime_tributario": "simples"})', verbose_name='Contexto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfis de Empresa',
                'ordering': ['name'],
            },
        ),
    ]
