# Generated by Django 6.0.3 on 2026-03-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm_type', models.CharField(choices=[('lei', 'Lei'), ('decreto', 'Decreto'), ('in_rfb', 'Instrução Normativa RFB'), ('resolucao', 'Resolução'), ('clt', 'CLT'), ('portaria', 'Portaria'), ('jurisprudencia', 'Jurisprudência'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('number', models.CharField(max_length=50, verbose_name='Número')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('official_link', models.URLField(blank=True, verbose_name='Link Oficial')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque se a norma foi revogada', verbose_name='Vigente')),
            ],
            options={
                'verbose_name': 'Norma Legal',
                'verbose_name_plural': 'Normas Legais',
                'ordering': ['-year', 'norm_type', 'number'],
            },
        ),
        migrations.CreateModel(
            name='LegalBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Artigo')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerto da Lei')),
                ('is_primary', models.BooleanField(default=False, help_text='A fundamentação primária desta rubrica', verbose_name='Base Principal')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_basis', to='catalog.rubric', verbose_name='Rubrica')),
                ('norm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legislation.legalnorm', verbose_name='Norma')),
            ],
            options={
                'verbose_name': 'Base Legal',
                'verbose_name_plural': 'Bases Legais',
                'ordering': ['-is_primary', 'norm__year'],
            },
        ),
    ]
