# Generated by Django 6.0.3 on 2026-03-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('provento', 'Provento'), ('desconto', 'Desconto'), ('informativo', 'Informativo'), ('base', 'Base de Cálculo')], max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EsocialNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('is_salary_nature', models.BooleanField(help_text='Define se possui natureza salarial para fins previdenciários', verbose_name='Natureza Salarial')),
            ],
            options={
                'verbose_name': 'Natureza eSocial',
                'verbose_name_plural': 'Naturezas eSocial',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicada')),
                ('last_legal_review', models.DateField(blank=True, null=True, verbose_name='Última Revisão Legal')),
                ('reviewed_by', models.CharField(blank=True, max_length=255, verbose_name='Revisado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Categoria')),
                ('esocial_nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.esocialnature', verbose_name='Natureza eSocial')),
            ],
            options={
                'verbose_name': 'Rubrica',
                'verbose_name_plural': 'Rubricas',
                'ordering': ['name'],
            },
        ),
    ]
