# Generated by Django 6.0.3 on 2026-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='related_rubrics',
            field=models.ManyToManyField(blank=True, help_text='Rubricas que frequentemente são consultadas junto com esta', to='catalog.rubric', verbose_name='Rubricas Relacionadas'),
        ),
    ]
